@startuml
:admin: -> (criar filial)
:admin: -> (consultar filial)
:admin: -> (excluir filial)
:admin: -> (criar cadastro cliente)
:admin: -> (excluir cadastro cliente)
:admin: -> (criar categoria )
:admin: -> (consultar categoria)
:admin: -> (excluir categoria)
:admin: -> (criar genero)
:admin: -> (consultar genero)
:admin: -> (excluir genero)
:admin: -> (criar pagamento)
:admin: -> (consultar pagamento)
:admin: -> (excluir pagamento)
:admin: -> (consultar data de entrega)
:admin: -> (criar data de entrega)
:admin: -> (aplicar multa)
:admin: -> (excluir multa)
:admin: -> (criar promo)
:admin: -> (excluir promo)
:admin: -> (abre caixa)
:admin: -> (fecha caixa final espediente)
:Atendente: -> (consultar filial)
:Atendente: -> (consultar categoria)
:Atendente: -> (consultar genero)
:Atendente: -> (criar cadastro do cliente)
:Atendente: -> (consultar pagamento)
:Atendente: -> (consultar promo)
:Atendente: -> (abir caixa)
:Atendente: -> (consultar data de entrega)
:Atendente: -> (consultar multa)
@enduml