@startuml
:admin: -> (criar data e hora de funcionamento)
:admin: -> (excluir data e hora de funcionamneto)
:admin: -> (criar filial)
:admin: -> (consultar filial)
:admin: -> (excluir filial)
:admin: -> (criar cadastro cliente)
:admin: -> (consultar cadastro cliente)
:admin  -> (atualizar cadastro cliente)
:admin: -> (excluir cadastro cliente)
:admin: -> (criar categoria )
:admin: -> (consultar categoria)
:admin: -> (excluir categoria)
:admin: -> (criar genero)
:admin: -> (consultar genero)
:admin: -> (excluir genero)
:admin: -> (criar pagamento)
:admin: -> (consultar pagamento)
:admin: -> (excluir pagamento)
:admin: -> (consultar data de entrega)
:admin: -> (criar data de entrega)
:admin: -> (aplicar multa)
:admin: -> (excluir multa)
:admin: -> (criar promo)
:admin: -> (excluir promo)
:admin: -> (abre caixa)
:admin: -> (fecha caixa final espediente)
:admin: -> (controle financeiro)
:admin: -> (criar historico vhs cliente)
:admin: -> (consultar historico vhs cliente)
:admin: -> (atualizar historico vhs cliente)
:admin: -> (excluir historico vhs cliente)
@enduml